apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-general-config
  namespace: custom-scheduler
data:
  config.yaml: "app:\n  env: \"dev\"\n\nlogging:\n  stdout: true\n  level: \"debug\"\n\nscheduler:
    \n  name: random-scheduler\n  namespace: sandbox\n"
