apiVersion: v1
kind: ConfigMap
metadata: 
  name: scheduler-general-config
  labels:
    app: custom-scheduler
data: 
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler: 
      name: random-scheduler
      namespace: sandbox

