app:
  env: "dev"

logging:
  stdout: true
  level: "debug"

scheduler:
  name: custom-scheduler
  namespace: custom-scheduler
  algorithm: "random"
  informerSyncPeriod: "15s"
  edgeAnnotationKey: "momtaz/cluster-type"
  edgeAnnotationValue: "edge"

connector:
  mode: "outside"
  masterURL: "192.168.76.2"
  kubeConfigPath: "/Users/sinashariati/.kube/config"
